name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
        apps: "scala-cli"
    - name: Test
      run: scala-cli --power test . --cross

  publish:
    if: github.event_name == 'push' && github.repository == 'coursier/get-cs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
        apps: "scala-cli"
    - run: .github/scripts/gpg-setup.sh
      env:
        PUBLISH_SECRET_KEY: ${{ secrets.PUBLISH_SECRET_KEY }}
    - name: Release
      run: scala-cli --power publish . --cross
      env:
        PUBLISH_SECRET_KEY: ${{ secrets.PUBLISH_SECRET_KEY }}
        PUBLISH_SECRET_KEY_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
